# Generated by Django 3.2.4 on 2021-09-27 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CNXProtect_Utl', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notesfile', models.FileField(null=True, upload_to='')),
            ],
        ),
        migrations.DeleteModel(
            name='Files',
        ),
    ]
