# Generated by Django 3.2.4 on 2021-12-16 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CNXProtect_Utl', '0004_auto_20211202_1253'),
    ]

    operations = [
        migrations.CreateModel(
            name='MSA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account', models.TextField()),
            ],
        ),
    ]
