# Generated by Django 3.2.4 on 2022-03-10 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CNXProtect_Utl', '0007_alter_add_keywords_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='File_pdf',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notesfile', models.FileField(upload_to='media')),
            ],
        ),
    ]
