# Generated by Django 3.2.4 on 2022-03-11 04:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CNXProtect_Utl', '0008_file_pdf'),
    ]

    operations = [
        migrations.RenameField(
            model_name='file_pdf',
            old_name='notesfile',
            new_name='notesfile1',
        ),
    ]
