# Generated by Django 3.2.4 on 2022-04-21 06:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CNXProtect_Utl', '0012_file1'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='File1',
            new_name='File_1',
        ),
        migrations.RenameField(
            model_name='file_1',
            old_name='notesfile',
            new_name='notesfile_1',
        ),
    ]
