# Generated by Django 3.2.4 on 2022-05-25 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CNXProtect_Utl', '0013_auto_20220421_1217'),
    ]

    operations = [
        migrations.CreateModel(
            name='Master_Data3',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notesfile_111', models.FileField(upload_to='Master_File3')),
            ],
        ),
    ]
